config/routes.rb
Rails.application.routes.draw do
  get 'books/show'
  get 'books/edit'
  get 'books/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  get 'home/top'
  get 'home/about'
  get 'home/after_login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'

  resources :books, only: [:create, :show, :index, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 199}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	def email_required?
		false
	end
	def email_changed?
    	false
	end

	attachment :profile_image

  	has_many :books, dependent: :destroy

  	validates :name, presence: true, length: {minimum: 2, maximum: 20}
  	validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_user!

	before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @user = current_user
    @books = Book.all
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	@book.save
  	if @book.save
      flash[:notice] = "Book was successfully created."
  		redirect_to book_path(@book.id)
  	else
  		render :index
  	end
  end

  def index
  	@user = current_user
  	@book = Book.new
  	@books = Book.all
  end

  def show
  	@user = Book.find(params[:id]).user
  	@book = Book.new
  	@current_book = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      flash[:notice] = "You cannot edit this book."
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	@book.update(book_params)
    if @book.update(book_params)
      flash[:notice] = "Book was successfully editted."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
    if @book.destroy
      flash[:notice] = "Book was successfully deleted."
      redirect_to books_path
  	else
      render :index
    end
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_before_action :authenticate_user!, only: [:top, :about]

  def top
  end

  def about
  end

  def after_login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = Book.where(user_id: @user.id)
	end

	def index
		@book = Book.new
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
			flash[:notice] = "You cannot edit this user."
			redirect_to user_path(current_user.id)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "User was successfully editted."
			redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<% if @book.errors.any? %>
		<div class="error_explanation">
			<h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
			<ul>
				<%= @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="row">
		<section class="col-xs-6 col-xs-offset-3 book-edit">
			<h1 class="edit-title">Editing Book</h1>

			<%= form_for @book do |f| %>
				<div class="field">
				    <%= f.label :title %><br />
				    <%= f.text_field :title, class:"col-xs-12 side-menu-form" %>
			    </div>
			    <div class="field">
				    <label>Opinion</label><br />
				    <%= f.text_area :body, class:"col-xs-12 side-menu-form" %>
			    </div>

			    <%= f.submit "Update Book", class:"btn btn-primary col-xs-12 side-menu-form" %>
			<% end %>

			<p class="form-links"><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></p>
		</section>
		<div class="col-xs-3"></div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">

	<% if @book.errors.any? %>
		<div class="error_explanation">
			<h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
			<ul>
				<%= @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<% if flash[:notice] %>
		<p class="flash"><%= flash[:notice] %></p>
	<% end %>

	<div class="row">
		<div class="col-xs-3 us-left">
			<section class="user-info">
				<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
				<table width="100%" class="table table-striped">
					<thead>
						<tr>
							<th width="40%">name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th width="40%">introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</thead>
				</table>
				<%= link_to "", edit_user_path(@user), class:"btn btn-default glyphicon glyphicon-wrench side-menu col-xs-12" %>
			</section>
			<section class="new-book">
				<h2>New book</h2>

				<%= form_for @book do |f| %>
					<div class="field">
					    <%= f.label :title %><br />
					    <%= f.text_field :title, class:"col-xs-12 side-menu-form" %>
				    </div>
				    <div class="field">
					    <label>Opinion</label><br />
					    <%= f.text_area :body, class:"col-xs-12 side-menu-form" %>
				    </div>

				    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12 side-menu-form" %>
				<% end %>

			</section>
		</div>
		<section class="col-xs-9 us-right">
			<h2>Books</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th colspan="1" width="20%"></th>
						<th width="40%">Title</th>
						<th width="40%">Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'40x40' %></td>
						<td><%= link_to "#{book.title}", book_path(book) %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</section>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	
	<% if flash[:notice] %>
		<p class="flash"><%= flash[:notice] %></p>
	<% end %>

	<div class="row">
		<div class="col-xs-3 us-left">
			<section class="user-info">
				<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
				<table width="100%" class="table table-striped">
					<thead>
						<tr>
							<th width="40%">name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th width="40%">introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</thead>
				</table>
				<% if @current_book.user == current_user %>
					<%= link_to "", edit_user_path(@user), class:"btn btn-default glyphicon glyphicon-wrench side-menu col-xs-12" %>
				<% else %>
					<%= link_to "", user_path(current_user), class:"btn btn-default glyphicon glyphicon-wrench side-menu col-xs-12" %>
				<% end %>
			</section>
			<section class="new-book">
				<h2>New book</h2>

				<%= form_for @book do |f| %>
					<div class="field">
					    <%= f.label :title %><br />
					    <%= f.text_field :title, class:"col-xs-12 side-menu-form" %>
				    </div>
				    <div class="field">
					    <label>Opinion</label><br />
					    <%= f.text_area :body, class:"col-xs-12 side-menu-form" %>
				    </div>

				    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12 side-menu-form" %>
				<% end %>

			</section>
		</div>
		<section class="col-xs-9 us-right">
			<h2>Book detail</h2>
			<table class="table table-striped">
				<% if @current_book.user == current_user %>
					<tbody>
						<tr>
							<td colspan="1" width="25%">
								<%= link_to user_path(@current_book.user) do %>
									<%= attachment_image_tag @current_book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %><br>
									<%= @current_book.user.name %>
								<% end %>
							</td>
							<td colspan="1" width="25%"><%= link_to "#{@current_book.title}", book_path(@current_book) %></td>
							<td colspan="1" width="25%"><%= @current_book.body %></td>
							<td colspan="1" width="12.5%"><%= link_to "edit", edit_book_path(@current_book), class:"btn-sm btn-success" %></td>
							<td colspan="1" width="12.5%"><%= link_to "Destroy", book_path(@current_book), class:"btn-sm btn-danger", method: :delete, data: { confirm: '削除しますか？' } %></td>
						</tr>
					</tbody>
				<% else %>
					<tbody>
						<tr>
							<td colspan="1" width="30%">
								<%= link_to user_path(@current_book.user) do %>
									<%= attachment_image_tag @current_book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %><br>
									<%= @current_book.user.name %>
								<% end %>
							</td>
							<td colspan="1" width="30%"><%= link_to "#{@current_book.title}", book_path(@current_book) %></td>
							<td colspan="1" width="40%"><%= @current_book.body %></td>
						</tr>
					</tbody>
				<% end %>
			</table>
		</section>
	</div>
</div>

app/views/home/about.html.erb
<div class="container">
	<h1 class="top-title">Welcome to <strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</strong></h1>
</div>

app/views/home/after_login.html.erb
<h1>Home#after_login</h1>
<p>Find me in app/views/home/after_login.html.erb</p>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

app/views/home/top.html.erb
<div class="container">
	<% if flash[:notice] %>
		<p class="flash"><%= flash[:notice] %></p>
	<% end %>
	<div class="col-xs-6 col-xs-offset-3 top-message">
		<h1 class="top-title">welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Bookers !!</h1>

		<p>In <strong><span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</strong>,</p>
		<p>you can share and exchange your opinions, inpressions, and emotions</p>
		<p>about various books!</p>

		<div class="row">
			<%= link_to 'Log in', new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1" %>
			<div class="col-xs-1"></div>
		</div>

		<div class="row">
			<%= link_to 'Sign up', new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1" %>
			<div class="col-xs-1"></div>
		</div>
	</div>
	<div class="col-xs-3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="header-logo">
          <h1>Bookers</h1>
        </div>
        <nav>
          <% if user_signed_in? %>
            <ul class="nav-list">
              <li class="nav-list-item">
                <%= link_to " Home", user_path(current_user.id),class:"glyphicon glyphicon-home" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " Users", users_path, class:"glyphicon glyphicon-user" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " Books", books_path, class:"glyphicon glyphicon-book" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " logout", destroy_user_session_path, class:"glyphicon glyphicon-log-out", method: :delete %>
              </li>
            </ul>
          <% else %>
            <ul class="nav-list">
              <li class="nav-list-item">
                <%= link_to " Home", root_path,class:"glyphicon glyphicon-home" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " About", home_about_path, class:"glyphicon glyphicon-link" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " sign up", new_user_registration_path, class:"glyphicon glyphicon-edit" %>
              </li>
              <li class="nav-list-item">
                <%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in" %>
              </li>
            </ul>
          <% end %>
         
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<h2>User info</h2>

	<%= form_for @user do |f| %>

		<% if @user.errors.any? %>
			<div class="error_explanation">
				<h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
				<ul>
					<%= @user.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
	      <%= f.label :name, class:"form-label" %>
	      <%= f.text_field :name, class:"form-control", autofocus: true %>
	    </div>

	    <div class="field">
	      <%= f.label :profile_image, class:"form-label" %><br>
	      <%= f.attachment_field :profile_image %>
	    </div>

	    <div class="field">
	      <%= f.label :introduction, class:"form-label" %><br>
	      <%= f.text_area :introduction %>
	    </div>

	    <%= f.submit "Update User", class:"user-edit-sub" %>

    <% end %>

</div>

app/views/users/index.html.erb
<div class="container">
	<% if flash[:notice] %>
		<p class="flash"><%= flash[:notice] %></p>
	<% end %>
	<div class="row">
		<div class="col-xs-3 us-left">
			<section class="user-info">
				<h2>User info</h2>
				<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
				<table width="100%" class="table table-striped">
					<thead>
						<tr>
							<th width="40%">name</th>
							<th><%= current_user.name %></th>
						</tr>
						<tr>
							<th width="40%">introduction</th>
							<th><%= current_user.introduction %></th>
						</tr>
					</thead>
				</table>
				<%= link_to "", edit_user_path(current_user), class:"btn btn-default glyphicon glyphicon-wrench side-menu col-xs-12" %>
			</section>
			<section class="new-book">
				<h2>New book</h2>

				<%= form_for @book do |f| %>
					<div class="field">
					    <%= f.label :title %><br />
					    <%= f.text_field :title, class:"col-xs-12 side-menu-form" %>
				    </div>
				    <div class="field">
					    <label>Opinion</label><br />
					    <%= f.text_area :body, class:"col-xs-12 side-menu-form" %>
				    </div>

				    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12 side-menu-form" %>
				<% end %>

			</section>
		</div>
		<section class="col-xs-9 us-right">
			<h2>Users</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th width="20%">image</th>
						<th width="40%">name</th>
						<th colspan="1" width="40%"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user)  %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</section>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<% if flash[:notice] %>
		<p class="flash"><%= flash[:notice] %></p>
	<% end %>
	<div class="row">
		<div class="col-xs-3 us-left">
			<section class="user-info">
				<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %>
				<table width="100%" class="table table-striped">
					<thead>
						<tr>
							<th width="40%">name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th width="40%">introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</thead>
				</table>
				<%= link_to "", edit_user_path, class:"btn btn-default glyphicon glyphicon-wrench side-menu col-xs-12" %>
			</section>
			<section class="new-book">
				<h2>New book</h2>

				<%= form_for @book do |f| %>
					<div class="field">
					    <%= f.label :title %><br />
					    <%= f.text_field :title, class:"col-xs-12 side-menu-form" %>
				    </div>
				    <div class="field">
					    <label>Opinion</label><br />
					    <%= f.text_area :body, class:"col-xs-12 side-menu-form" %>
				    </div>

				    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12 side-menu-form" %>
				<% end %>

			</section>
		</div>
		<section class="col-xs-9 us-right">
			<h2>Books</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th colspan="1" width="20%"></th>
						<th width="40%">Title</th>
						<th width="40%">Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %></td>
						<td><%= link_to "#{book.title}", book_path(book) %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</section>
	</div>
</div>